#%RAML 0.8
---
title: scenario-4
version: 1.0
baseUri: http://localhost:8002/api
/overwrite-validations:
  get:
    queryParameters:
      param:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          param:
            type: string
            required: true
            minLength: 3
            maxLength: 3
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-03/schema",
            "properties": {
              "id": {
                "description": "Identifier",
                "maxLength": 3,
                "minLength": 3,
                "type": "string"
              }
            },
            "type": "object",
            "name": "resource"
          }
    responses:
      201:
        body:
          application/json:
  /{id}:
    uriParameters:
      id:
        type: number
        minimum: 10
        maximum: 10
    get:
      responses:
        200:
          body:
            application/json:
    put:
      headers:
        header:
          type: string
          enum: [a, b]
      body:
        application/json:
      responses:
        204: