#%RAML 0.8
---
title: scenario-1
version: 1.0
baseUri: http://localhost:8000/api
/resources:
  get:
    responses:
      200:
        headers:
          header:
            default: GET
        body:
          application/json:
            example: |
              [{
                "id": "1",
                "description": "description"
              },
              {
                "id": "2",
                "description": "description"
              }]
      500:
  post:
    body:
      application/json:
    responses:
      201:
        headers:
          header:
            default: POST
        body:
          application/json:
            example: |
              {
                "description": "description"
              }
      500:
  put:
    body:
      application/json:
    responses:
      204:
        headers:
          header:
            default: PUT
      500:
  head:
    responses:
      204:
        headers:
          header:
            default: HEAD
          header2:
      500:
  patch:
    body:
      application/json:
    responses:
      204:
        headers:
          header:
            default: PATCH
      500:
  /{id}:
    get: 
      responses:
        200:
          headers:
            header:
              default: GET
          body:
            application/json:
              example: |
                {
                  "id": "1",
                  "description": "description"
                }
        500:
    delete:
      responses:
        204:
          headers:
            header:
              default: DELETE
    head:
      responses:
        204:
          headers:
            header:
              default: HEAD
        500:
/empty:
  get:
    responses:
      200:
        headers:
          header:
            default: GET