#%RAML 0.8
---
title: validations-json-schema
version: 1.0
baseUri: http://localhost:3000/api
/resources:
  post:
    body:
      application/xml:
        schema: |
          <?xml version="1.0" encoding="ISO-8859-1" ?>
            <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
             elementFormDefault="qualified" xmlns="http://mulesoft.com/schemas/soccer"
             targetNamespace="http://mulesoft.com/schemas/soccer">
            <xs:element name="league">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="name" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:schema>