#%RAML 0.8
---
title: validations-query-parameters
version: 1.0
baseUri: http://localhost:3000/api
/string:
  get:
    queryParameters:
      param:
        type: string
        required: true
        minLength: 3
        maxLength: 3
  /enum:
    get:
      queryParameters:
        param:
          type: string
          enum: [AAA, BBB]
  /pattern:
    get:
      queryParameters:
        param:
          type: string
          pattern: '[a-z]'
  /empty:
    get:
      queryParameters:
        param:
          type: string
/integer:
  get:
    queryParameters:
      param:
        type: integer
        minimum: 10
        maximum: 10
        required: true
/number:
  get:
    queryParameters:
      param:
        type: number
        minimum: 10
        maximum: 11
        required: true
  /empty:
    get:
      queryParameters:
        param:
          type: number
          required: true
/boolean:
  get:
    queryParameters:
      param:
        type: boolean
        required: true
/date:
  get:
    queryParameters:
      param:
        type: date
        required: true
