#%RAML 0.8
---
title: validations-header
version: 1.0
baseUri: http://localhost:3000/api
/string:
  get:
    headers:
      Header:
        type: string
        required: true
        minLength: 3
        maxLength: 3
  /enum:
    get:
      headers:
        Header:
          type: string
          enum: [AAA, BBB]
  /pattern:
    get:
      headers:
        Header:
          type: string
          pattern: '[a-z]'
/integer:
  get:
    headers:
      Header:
        type: integer
        minimum: 10
        maximum: 10
        required: true
/number:
  get:
    headers:
      Header:
        type: number
        minimum: 10
        maximum: 10
        required: true
/boolean:
  get:
    headers:
      Header:
        type: boolean
        required: true
/date:
  get:
    headers:
      Header:
        type: date
        required: true
