#%RAML 0.8
---
title: validations-uri-parameters
version: 1.0
baseUri: http://localhost:3000/api
/string:
  /{id}:
    uriParameters:
      id:
        type: string
        required: true
        minLength: 3
        maxLength: 3
  /enum:
    /{id}:
      uriParameters:
        id:
          type: string
          enum: [AAA, BBB]
  /pattern:
    /{id}:
      uriParameters:
        id:
          type: string
          pattern: '[a-z]'    
/integer:
  /{id}:
    uriParameters:
      id:
        type: integer
        minimum: 10
        maximum: 10
/number:
  /{id}:
    uriParameters:
      id:
        type: number
        minimum: 10
        maximum: 10
/boolean:
  /{id}:
    uriParameters:
      id:
        type: boolean
/date:
  /{id}:
    uriParameters:
      id:
        type: date