#%RAML 0.8
---
title: validations-form-parameters
version: 1.0
baseUri: http://localhost:3000/api
/string:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          param:
            type: string
            required: true
            minLength: 3
            maxLength: 3
  /enum:
    post:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            param:
              type: string
              enum: [AAA, BBB]
  /pattern:
    post:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            param:
              type: string
              pattern: '[a-z]'    
/integer:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          param:
            type: integer
            minimum: 10
            maximum: 10
/number:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          param:
            type: number
            minimum: 10
            maximum: 10
/boolean:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          param:
            type: boolean
            required: true
/date:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          param:
            type: date
            required: true