#%RAML 0.8
---
title: validations-json-schema
version: 1.0
baseUri: http://localhost:3000/api
/resources:
  post:
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-03/schema",
            "properties": {
              "id": {
                "description": "Identifier",
                "maxLength": 3,
                "minLength": 3,
                "type": "string"
              }
            },
            "type": "object",
            "name": "resource"
          }