#%RAML 0.8
---
title: validations
version: 1.0
baseUri: http://localhost:3000/api
/string:
  get:
  /{id}:
    uriParameters:
      id:
        type: string
        minLength: 3
        maxLength: 3
/stringWithEnum:
  get:
  /{id}:
    uriParameters:
      id:
        type: string
        enum: [AAA, BBB]
/stringWithPattern:
  get:
  /{id}:
    uriParameters:
      id:
        type: string
        pattern: '[a-z]'
/integer:
  get:
  /{id}:
    uriParameters:
      id:
        type: integer
        minimum: 10
        maximum: 10
/integerType:
  get:
  /{id}:
    uriParameters:
      id:
        type: integer
/number:
  get:
  /{id}:
    uriParameters:
      id:
        type: number
        minimum: 10
        maximum: 10
/numberType:
  get:
  /{id}:
    uriParameters:
      id:
        type: number