#%RAML 0.8
---
title: well-formed-example
version: 1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:3000/api
securitySchemes:
  - oauth_2_0:
      type: OAuth 2.0
      describedBy:
          headers:
              Authorization:
                  type: string
          queryParameters:
              access_token:
                  type: string
          responses:
              401:
              403:
      settings:
        authorizationUri: https://www.dropbox.com/1/oauth2/authorize
        accessTokenUri: https://api.dropbox.com/1/oauth2/token
        authorizationGrants: [ code, token ]
/resource:
  get:
  post:
    body:
      application/json:
        example: |
          {
            "name": "Barcelona",
            "id": "BAR",
            "homeCity": "Barcelona",
            "stadium": "Camp Nou"
          }
  put:
  delete:
  head:
  patch:
  /{resourceId}:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                [{
                  "id": "example"
                }]
            application/xml:
/resource2: