#%RAML 0.8
---
title: scenario-2
version: 1.0
baseUri: http://localhost:8001/api
/validations:
  get:
    queryParameters:
      param:
        type: string
        required: true
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          param:
            type: string
            required: true
            minLength: 3
            maxLength: 3
  put:
    headers:
      header:
        type: string
        enum: [a, b]
  /{id}:
    uriParameters:
      id:
        type: number
        minimum: 10
        maximum: 10
    get:
