#%RAML 1.0
title: Messages API

/message:
  post:
    description: Send a message to a user
    body:
      application/json:
        properties:
          userId:
            type: string
            pattern: "[a-zA-Z0-9]+"
