#%RAML 0.8
---
title: scenario-8
version: 1.0
baseUri: http://localhost:7/api2
/overwrite:
  get:
    responses:
      200:
        body:
          application/json:
  post:
    body:
      application/json:
    responses:
      201:
        body:
          application/json:
  head:
    responses:
      204:
  /{id}:
    get: 
      responses:
        200:
          body:
            application/json:
    put:
      body:
        application/json:
      responses:
        204:
    patch:
      body:
        application/json:
      responses:
        204:
    delete:
      responses:
        204:
/not-overwritten:
  get:
    responses:
      200:
        body:
          application/json: